name: ChapterCheck
options:
  bundleIdPrefix: com.chaptercheck
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"

packages:
  ConvexMobile:
    url: https://github.com/get-convex/convex-swift
    from: 0.7.0
  Clerk:
    url: https://github.com/clerk/clerk-ios
    from: 1.0.0

targets:
  ChapterCheck:
    type: application
    platform: iOS
    sources:
      - path: ChapterCheck
        excludes:
          - "*.xcassets"
      - path: ChapterCheck/Assets.xcassets
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chaptercheck.ios
        INFOPLIST_FILE: ChapterCheck/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: ConvexMobile
      - package: Clerk
        product: ClerkKit
